adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('', adminapp.MainView.as_view(), name='main_admin'),
    path('users/', adminapp.UserListView.as_view(), name='users'),
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('categories/', adminapp.CategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('habs/create/', adminapp.HabCreateView.as_view(), name='hab_create'),
    path('habs/', adminapp.HabsListView.as_view(), name='habs'),
    path('habs/update/<uuid:pk>/', adminapp.HabUpdateView.as_view(), name='hab_update'),
    path('habs/delete/<uuid:pk>/', adminapp.HabDeleteView.as_view(), name='hab_delete'),

    path('comments/create/', adminapp.CommentCreateView.as_view(), name='comment_create'),
    path('comments/', adminapp.CommnetsListView.as_view(), name='comments'),
    path('comments/update/<int:pk>/', adminapp.CommentUpdateView.as_view(), name='comment_update'),
    path('comments/delete/<int:pk>/', adminapp.CommentDeleteView.as_view(), name='comment_delete'),

    # path('news/', adminapp.NewsListView.as_view(), name='news'),
    # path('news/create/', adminapp.NewsCreateView.as_view(), name='news_create'),
    # path('news/update/<int:pk>/', adminapp.NewsUpdateView.as_view(), name='news_update'),
    # path('news/delete/<int:pk>/', adminapp.NewsDeleteView.as_view(), name='news_delete'),

    path('moder/', adminapp.ModerListView.as_view(), name='moder'),
    path('moder/hab/<uuid:pk>/', adminapp.ApproveHab.as_view(), name='approve_hab'),
    # path('moder/news/<int:pk>/', adminapp.ApproveNews.as_view(), name='approve_news'),
    path('moder/notify/delete/<int:pk>/', adminapp.NotifyDeleteView.as_view(), name='notify_delete'),
    path('moder/block/<int:pk>', adminapp.UserBlock.as_view(), name='user_block'),
]

authapp/urls.py
from django.urls import path

from authapp import views as authapp
from authapp.views import LoginUserView, LogoutUserView, RegisterUserView, VerifyView, ProfileEditView, UserDetailView, \
    UserChangePassword, notification_view
from django.urls import include, re_path

app_name = 'authapp'

urlpatterns = [
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('register/', RegisterUserView.as_view(), name='register'),
    # path('account/', authapp.account, name='account'),

    path('messages/', authapp.messages, name='messages'),




    path('edit/<int:pk>/', ProfileEditView.as_view(), name='edit'),


    path('verify/<email>/<activation_key>', VerifyView.as_view(), name='verify'),
    path('profile/<int:pk>', UserDetailView.as_view(), name='profile'),
    path('change-password/', UserChangePassword.as_view(), name='change_pass'),
    path('notification/<int:user_id>/', authapp.notification_view, name='user_notification'),
]

habapp/urls.py
from django.urls import path

from habapp.views import IndexView, HabDetailView, \
    HabCreateView, HabUpdateView, HabDeleteView, like_hab, \
    CategoryHabView, HabListView, HabPublished


app_name = 'habapp'

urlpatterns = [
    path('', IndexView.as_view(), name='main'),
    path('index/', IndexView.as_view(), name='main'),
    path('new/', HabCreateView.as_view(), name='add'),
    path('list/', HabListView.as_view(), name='list'),
    path('<uuid:pk>/', HabDetailView.as_view(), name='detail'),
    path('hab/<uuid:pk>/edit/', HabUpdateView.as_view(), name='edit'),
    path('hab/<uuid:pk>/delete/', HabDeleteView.as_view(),
         name='delete'),
    path('<uuid:pk>/like/', like_hab, name='like-hab'),
    path('category/<int:pk>', CategoryHabView.as_view(), name='hab_category'),
    path('<uuid:pk>/published/', HabPublished.as_view(), name='public'),
]

habrmirror/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

import mainapp
from mainapp.views import about, help

urlpatterns = [
    path('admin/', admin.site.urls),
    path('_admin/', include('adminapp.urls', namespace='_admin')),
    path('temp/', include('mainapp.urls')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('habapp.urls', namespace='hab')),
    # path('', include('social_django.urls', namespace='social')),
    # path('', include('searchapp.urls', namespace='search')),
    path('notification/', include('notificationapp.urls', namespace='notify')),
    path('about/', about, name='about'),
    path('help/', help, name='help'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path, include

from mainapp.views import main, help

app_name = 'mainapp'

urlpatterns = [
    path('', main, name='main'),
    path('index/', main),
]

mainapp/models.py
# from django.db import models
# from django.utils import timezone
#
# from authapp.models import HabUser
#
#
# class HabCategory(models.Model):
#     """Модель описывает категории статей"""
#     name = models.CharField(max_length=64, unique=True)
#     description = models.TextField(blank=True)
#
#     class Meta:
#         verbose_name_plural = 'Hab Categories'
#
#     def __str__(self):
#         return self.name

mainapp/views.py
from django.shortcuts import render

from core.context_service import context_update
from habapp.models import Like
from mainapp.service_mainapp import last_hub


def main(request):
    title = "Main"

    content = {"title": title}

    return render(request, "mainapp/index.html", content)


def about(request):
    title = "About"

    content = {"title": title}

    return render(request, "mainapp/about.html", content)


def help(request):
    title = "help"

    content = {"title": title}

    return render(request, "mainapp/help.html", content)

mainapp/templates/mainapp/includes/head_menu.html
<div class="fixed-top">
    <div>
      <nav role="navigation">
        <div id="menuToggle">
          <input type="checkbox" />
          <span></span>
          <span></span>
          <span></span>

          <ul id="menu">
            <li><a href="{% url 'index' %}">Главная</a></li>
            {%for category in hab_category%}
            <li><a href="{% url 'category' category.id  %}">{{category.name}}</a></li>
            {%endfor%}
            {% if user.is_authenticated %}
             <li><a href="{% url 'logout' %}">Выход</a></li>
            {% else %}
              <li><a href="{% url 'login' %}">Вход</a></li>
            {% endif %}


          </ul>
        </div>

      </nav>
    </div>

    <header>
        <div class="header_center">
          <a class="header_title"></a>
        </div>
        <div class="header_center">
          <a class="header_title line-after-heading" href="{% url 'index' %}">Habrmirror</a>

        </div>


        <div class="header_right">
          <a class="link-secondary" href="#" aria-label="Search">
            <svg class="mx-3"
                 xmlns="http://www.w3.org/2000/svg"
                 width="20"
                 height="20"
                 fill="none"
                 stroke="currentColor"
                 stroke-linecap="round"
                 stroke-linejoin="round"
                 stroke-width="2"
                 role="img"
                 viewBox="0 0 24 24">
              <title>Search</title>
              <circle cx="10.5" cy="10.5" r="7.5"/>
              <path d="M21 21l-5.2-5.2"/>
            </svg>
          </a>
          {% if user.is_authenticated %}
            <a class="btn btn-sm btn-outline-secondary"
             href="{% url 'login' %}"
             style="--bs-btn-color: white; --bs-btn-font-size: 1rem;">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-lines-fill" viewBox="0 0 16 16">
  <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm-5 6s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zM11 3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5zm.5 2.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1h-4zm2 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-2zm0 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-2z"/>
</svg> {{user.username}}
          </a>
            {% else %}
            <a class="btn btn-sm btn-outline-secondary"
             href="{% url 'login' %}"
             style="--bs-btn-color: white; --bs-btn-font-size: 1rem;">Sign up
          </a>
            {% endif %}
        </div>


    </header>
</div>

mainapp/templates/mainapp/includes/inc_article_category_list.html
 <!-- ======= Services Section ======= -->
 <section id="services" class="services">
     <div class="container">
         <div class="row">
             {% for category in categories %}
             <div class="col-lg-3 col-md-6">
                 <div class="icon-box h-100">
                     <div class="icon"><i class="bx bx-file"></i></div>
                     <h4><a href="{% url 'hab:hab_category' category.pk %}">{{ category }}</a></h4>
                 </div>
             </div>
             {% endfor %}
         </div>
     </div>
 </section><!-- End Services Section -->

mainapp/templates/mainapp/includes/inc_article_list.html
<!-- ======= Featured Section ======= -->
<section id="blog" class="blog">
    <div class="container">
        <div class="row">

        {% block content %}
            {% for hab in hab %}
                <article class="entry">
                    <h2 class="entry-title">
                        <a href="{% url 'hab:detail' hab.pk %}">
                            {{ hab.title }}
                        </a>
                    </h2>
                    <div class="entry-meta">
                        <ul>
                            <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a
                                    href="{% url 'auth:profile' hab.author.pk %}">{{ hab.author }}</a></li>
                            <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a
                                    href="{% url 'hab:detail' hab.pk %}">
                                {% if hab.publication_date %}
                                <time datetime="2020-01-01">{{ hab.publication_date }}</time>
                                {% else %}
                                <time datetime="2020-01-01">{{ hab.created }}</time>
                                {% endif %}
                            </a></li>
                            <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a
                                    href="{% url 'hab:detail' hab.pk %}">Комментариев: {{ hab.comments_habs.all.count }}</a>
                            </li>
                            <li class="d-flex align-items-center"><i class="bi bi-hand-thumbs-up"></i> <a
                                    href="{% url 'hab:detail' hab.pk %}">{{ hab.liked.all.count }}</a>
                            </li>
                            <li class="d-flex align-items-center"><i class="bi bi-bar-chart"></i> <a
                                    href="{% url 'hab:detail' hab.pk %}">Рейтинг: {{ hab.rating }}</a>
                            </li>
                        </ul>
                    </div>
                    <div class="entry-content">
                        {{ hab.content | safe | truncatechars_html:500 }}
                    </div>
                </article>
            {% endfor %}
        {% endblock content %}
        {% include "paginator.html" %}
        </div>
    </div>
</section><!-- End Featured Section -->

mainapp/templates/mainapp/includes/inc_footer.html
<footer id="footer">
    <div class="footer-top">
        <div class="container">
            <div class="row" style="height: 115px;">

                <div class="col-lg-3 col-md-6 footer-contact">
                    <h4>Контакты</h4>
                    <p>
                        <strong>Phone:</strong> +7 123 123 1231<br>
                        <strong>Email:</strong> support@geekbrains.ru<br>
                    </p>

                </div>

                <div class="col-lg-3 col-md-6 footer-contact">
                    <h4>Поддержка</h4>
                    <p>
                        <a href="{% url 'about' %}" style="color: white" >О нас</a> <br>
                        <a href="{% url 'help' %}" style="color: white" >Помощь</a><br>
                    </p>
                </div>



            </div>
            <div class="copyright">
                &copy; Copyright <strong><span>HabrMirror</span></strong>. All Rights Reserved
            </div>
        </div>
    </div>
</footer>

mainapp/templates/mainapp/includes/inc_hab_category_list.html
 <!-- ======= Services Section ======= -->
 <section id="services" class="services">
     <div class="container">
         <div class="row">
             {% for category in categories %}
             <div class="col-lg-3 col-md-6">
                 <div class="icon-box h-100">
                     <div class="icon"><i class="bx bx-file"></i></div>
                     <h4><a href="{% url 'hab:hab_category' category.pk %}">{{ category }}</a></h4>
                 </div>
             </div>
             {% endfor %}
         </div>
     </div>
 </section><!-- End Services Section -->

mainapp/templates/mainapp/includes/inc_hab_list.html
<!-- ======= Featured Section ======= -->
<section id="blog" class="blog">
    <div class="container">
        <div class="row">

        {% block content %}
            {% for hab in object_list %}
                <article class="entry">
                    <h2 class="entry-title">
                        <a href="{% url 'hab:detail' hab.pk %}">
                            {{ hab.title }}
                        </a>
                    </h2>
                    <div class="entry-meta">
                        <ul>
                            <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a
                                    href="{% url 'auth:profile' hab.author.pk %}">{{ hab.author }}</a></li>
                            <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a
                                    href="{% url 'hab:detail' hab.pk %}">
                                {% if hab.publication_date %}
                                <time datetime="2020-01-01">{{ hab.publication_date }}</time>
                                {% else %}
                                <time datetime="2020-01-01">{{ hab.created }}</time>
                                {% endif %}
                            </a></li>
                            <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a
                                    href="{% url 'hab:detail' hab.pk %}">Комментариев: {{ hab.comments_habs.all.count }}</a>
                            </li>
                            <li class="d-flex align-items-center"><i class="bi bi-hand-thumbs-up"></i> <a
                                    href="{% url 'hab:detail' hab.pk %}">{{ hab.liked.all.count }}</a>
                            </li>
                            <li class="d-flex align-items-center"><i class="bi bi-bar-chart"></i> <a
                                    href="{% url 'hab:detail' hab.pk %}">Рейтинг: {{ hab.rating }}</a>
                            </li>
                        </ul>
                    </div>
                    <div class="entry-content">
                        {{ hab.content | safe | truncatechars_html:500 }}
                    </div>
                </article>
            {% endfor %}
        {% endblock content %}
        {% include "paginator.html" %}
        </div>
    </div>
</section><!-- End Featured Section -->

mainapp/templates/mainapp/includes/inc_menu.html
{% load static %}

<header id="header" class="d-flex align-items-center">
    <div class="container d-flex justify-content-between align-items-center">
        <div class="logo">
            <h1><a href="{% url 'hab:main' %}">HabrMirror</a></h1>
        </div>
        <nav id="navbar" class="navbar">
            <ul>
                <li><a href="#">Новости</a></li>
                {% for category in categories %}
                <li><a href="{% url 'hab:hab_category' category.pk %}">{{ category }}</a></li>
                {% endfor %}
                <form class="form-inline my-2 my-lg-0 d-flex align-items-center"
                        method="POST" style="margin-left: 30px;" action="#">
                    {% csrf_token %}
                    <button class="btn  my-2 my-sm-0" name="searched" style="color: #6c757d;">
                      <span class="fa fa-search form-control-feedback"></span>
                  </button>
                </form>
                <li class="dropdown">
                    {% if user.is_authenticated %}
                    <a href="#">{{ user.username }}</a>
                    {% else %}
                    <a href="#">Войти</a>
                    {% endif %}
                   <ul>
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'auth:profile' user.pk %}">Профиль</a></li>
                            {% if not user.role == 'U' or user.is_superuser %}
                                <li><a href="{% url '_admin:main_admin' %}">Админка</a></li>
                            {% endif %}
                            <li><a href="{% url 'hab:list' %}">Все мои статьи</a></li>
                            {% if not user.check_block %}
                            <li><a href="{% url 'hab:add' %}">Добавить статью</a></li>
                            {% endif %}
                            <li><a href="{% url 'auth:logout' %}">Выйти</a></li>
                        {% else %}
                            <li><a href="{% url 'auth:login' %}">Войти</a></li>
                            <li><a href="{% url 'auth:register' %}">Регистрация</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->
    </div>
</header><!-- End Header -->

mainapp/templates/mainapp/includes/inc_slider.html
{% load static %}
<!-- ======= Блок самых читаемых статей ======= -->
<section id="hero">
    <div class="hero-container">
        <div id="heroCarousel" data-bs-interval="5000" class="carousel slide carousel-fade" data-bs-ride="carousel">
            <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>
            <div class="carousel-inner" role="listbox">
                <!-- Slide 1 -->


                 <div class="carousel-item" style="background: {% static 'assets/img/slide/slide-1.jpg' %}">
                        <div class="carousel-container">
                            <div class="carousel-content">
                                <h2 class="animate__animated animate__fadeInDown">Создать<span> статью</span></h2>
                                {% if user.is_authenticated %}
                                <a href="{% url 'hab:add' %}"
                                   class="btn-get-started animate__animated animate__fadeInUp">Создать</a>
                                {% else %}
                                <a href="{% url 'auth:login' %}" class="btn-get-started animate__animated animate__fadeInUp">Войдите или зарегистрируйтесь</a>

                                {% endif %}
                            </div>
                        </div>
                    </div>

                <!-- Slide 2 -->
                <div class="carousel-item active" style="background: {% static 'assets/img/slide/slide-2.jpg' %}">
                    <div class="carousel-container">
                        <div class="carousel-content">
                            <h2 class="animate__animated fanimate__adeInDown">Поиск <span> статьи</span></h2>
                            <a href="#" class="btn-get-started animate__animated animate__fadeInUp">Найти</a>
                        </div>
                    </div>
                </div>
                <!-- Slide 3 -->
                <div class="carousel-item" style="background: {% static 'assets/img/slide/slide-3.jpg' %}">
                    <div class="carousel-container">
                        <div class="carousel-content">
                            <h2 class="animate__animated animate__fadeInDown">Образовательный портал <span> Geekbrains</span></h2>
                            <p class="animate__animated animate__fadeInUp">Реклама нашего партнера</p>
                            <a href="https://gb.ru/" class="btn-get-started animate__animated animate__fadeInUp">Прочитать больше о
                                проекте</a>
                        </div>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#heroCarousel" role="button" data-bs-slide="prev">
                <span class="carousel-control-prev-icon bi bi-chevron-left" aria-hidden="true"></span>
            </a>
            <a class="carousel-control-next" href="#heroCarousel" role="button" data-bs-slide="next">
                <span class="carousel-control-next-icon bi bi-chevron-right" aria-hidden="true"></span>
            </a>
        </div>
    </div>
</section><!-- End Hero -->

mainapp/templates/mainapp/includes/inc_topbar.html
{% load static %}
<!-- ======= Top Bar ======= -->
<section id="topbar" class="d-flex align-items-center">
    <div class="container">
        <div class="row">
            <div class="col-md-7 contact-info d-flex">
                <i class="bi bi-envelope d-flex align-items-center"><a href="mailto:support@geekbrains.ru">support@geekbrains.ru</a></i>
                <i class="bi bi-phone d-flex align-items-center ms-4"><span>+7 911 111 1111</span></i>
            </div>
            <div class="col-md-5 search-form d-flex justify-content-end pt-3 pt-md-0">
                <form method="POST" action="#">
                    {% csrf_token %}
                    <div class="search-input-wrapper">
                        <input type="search"
                               placeholder="Найти..."
                               aria-label="Search"
                               name="searched"
                   style="border: 0px;">
                    </div>
                    <button type="submit">
                        <i class="bi bi-search"></i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</section>