adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('', adminapp.MainView.as_view(), name='main_admin'),
    path('users/', adminapp.UserListView.as_view(), name='users'),
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('categories/', adminapp.CategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('habs/create/', adminapp.HabCreateView.as_view(), name='hab_create'),
    path('habs/', adminapp.HabsListView.as_view(), name='habs'),
    path('habs/update/<uuid:pk>/', adminapp.HabUpdateView.as_view(), name='hab_update'),
    path('habs/delete/<uuid:pk>/', adminapp.HabDeleteView.as_view(), name='hab_delete'),

    path('comments/create/', adminapp.CommentCreateView.as_view(), name='comment_create'),
    path('comments/', adminapp.CommnetsListView.as_view(), name='comments'),
    path('comments/update/<int:pk>/', adminapp.CommentUpdateView.as_view(), name='comment_update'),
    path('comments/delete/<int:pk>/', adminapp.CommentDeleteView.as_view(), name='comment_delete'),

    # path('news/', adminapp.NewsListView.as_view(), name='news'),
    # path('news/create/', adminapp.NewsCreateView.as_view(), name='news_create'),
    # path('news/update/<int:pk>/', adminapp.NewsUpdateView.as_view(), name='news_update'),
    # path('news/delete/<int:pk>/', adminapp.NewsDeleteView.as_view(), name='news_delete'),

    path('moder/', adminapp.ModerListView.as_view(), name='moder'),
    path('moder/hab/<uuid:pk>/', adminapp.ApproveHab.as_view(), name='approve_hab'),
    # path('moder/news/<int:pk>/', adminapp.ApproveNews.as_view(), name='approve_news'),
    path('moder/notify/delete/<int:pk>/', adminapp.NotifyDeleteView.as_view(), name='notify_delete'),
    path('moder/block/<int:pk>', adminapp.UserBlock.as_view(), name='user_block'),
]

habapp/urls.py
from django.urls import path

from habapp.views import IndexView, HabDetailView, \
    HabCreateView, HabUpdateView, HabDeleteView, like_hab, \
    CategoryHabView, HabListView, HabPublished


app_name = 'habapp'

urlpatterns = [
    path('', IndexView.as_view(), name='main'),
    path('index/', IndexView.as_view(), name='main'),
    path('new/', HabCreateView.as_view(), name='add'),
    path('list/', HabListView.as_view(), name='list'),
    path('<uuid:pk>/', HabDetailView.as_view(), name='detail'),
    path('hab/<uuid:pk>/edit/', HabUpdateView.as_view(), name='edit'),
    path('hab/<uuid:pk>/delete/', HabDeleteView.as_view(),
         name='delete'),
    path('<uuid:pk>/like/', like_hab, name='like-hab'),
    path('category/<int:pk>', CategoryHabView.as_view(), name='hab_category'),
    path('<uuid:pk>/published/', HabPublished.as_view(), name='public'),
]

habrmirror/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

import mainapp
from mainapp.views import about, help

urlpatterns = [
    path('admin/', admin.site.urls),
    path('_admin/', include('adminapp.urls', namespace='_admin')),
    path('temp/', include('mainapp.urls')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('habapp.urls', namespace='hab')),
    # path('', include('social_django.urls', namespace='social')),
    # path('', include('searchapp.urls', namespace='search')),
    path('notification/', include('notificationapp.urls', namespace='notify')),
    path('about/', about, name='about'),
    path('help/', help, name='help'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


from authapp.models import HabUser, HabProfile
from habapp.models import Category, Hab
from commentapp.models import Comments
# from news.models import News

CHECK_LIST = ['is_active', 'is_delete', 'is_staff', 'is_deleted',
              'comment_moderation', 'approve']


def add_class_html(fields):
    for field_name, field in fields.items():
        if field_name in CHECK_LIST:
            field.widget.attrs['class'] = 'form-chek'
            field.help_text = ''
            continue
        else:
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = HabUser
        fields = ('username', 'first_name', 'last_name', 'email', 'is_active', 'role', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_class_html(self.fields)


class UserCreateForm(UserCreationForm):
    class Meta:
        model = HabUser
        fields = ('username', 'email', 'first_name', 'last_name', 'password1',
                  'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_class_html(self.fields)


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = HabProfile
        fields = ('tagline', 'gender', 'birthday', 'zone')

    birthday = forms.DateField(label='Дата рождения',
                               required=True,
                               widget=forms.SelectDateWidget(years=range(1930, 2015)),
                               )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_class_html(self.fields)


class CategoryCreateForm(forms.ModelForm):
    class Meta:
        model = Category
        exclude = ()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_class_html(self.fields)


class HabCreateForm(forms.ModelForm):
    class Meta:
        model = Hab
        fields = ('title', 'category', 'content', 'author',
                  'image', 'status')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_class_html(self.fields)


class HabUpdateForm(forms.ModelForm):
    class Meta:
        model = Hab
        # fields = ('title', 'category', 'content', 'author', 'image', 'status')
        exclude = ['uid', 'liked', 'publication_date', 'approve']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_class_html(self.fields)


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comments
        exclude = ['comment_moderation', 'is_active']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_class_html(self.fields)


class CommentUpdateForm(forms.ModelForm):
    class Meta:
        model = Comments
        exclude = ()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_class_html(self.fields)

#
# class NewsCreateForm(forms.ModelForm):
#     class Meta:
#         model = News
#         fields = ('title', 'anons', 'full_text', 'image')
#
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         add_class_html(self.fields)

#
# class NewsUpdateForm(forms.ModelForm):
#     class Meta:
#         model = News
#         fields = ('title', 'anons', 'full_text', 'author','image')
#
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         add_class_html(self.fields)


class ApproveHabForm(forms.ModelForm):
    class Meta:
        model = Hab
        fields = ()

#
# class ApproveNewsForm(forms.ModelForm):
#     class Meta:
#         model = Hab
#         fields = ()

adminapp/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
from django.utils import timezone

from commentapp.models import Comments
# from news.models import News
from .forms import UserUpdateForm, UserCreateForm, ProfileUpdateForm, CategoryCreateForm, HabCreateForm, \
    HabUpdateForm, CommentCreateForm, CommentUpdateForm,ApproveHabForm
# from .forms import ApproveNewsForm,NewsCreateForm, NewsUpdateForm
from .mixins import UserIsPersonalMixin, UserIsAdminMixin
from habapp.models import Category, Hab
from authapp.models import HabUser
from .models import NotifyComment


# главная страница админки
class MainView(UserIsPersonalMixin, TemplateView):
    template_name = 'adminapp/main_admin.html'


class UserListView(UserIsPersonalMixin, ListView):
    model = HabUser
    template_name = 'adminapp/users/users.html'
    context_object_name = 'objects'
    paginate_by = 10
    ordering = ['role']


class UserCreateView(UserIsAdminMixin, CreateView):
    model = HabUser
    form_class = UserCreateForm
    template_name = 'adminapp/users/user_create.html'
    success_url = reverse_lazy('_admin:users')


class UserUpdateView(UserIsAdminMixin, UpdateView):
    model = HabUser
    template_name = 'adminapp/users/user_update.html'
    success_url = reverse_lazy('_admin:users')
    form_class = UserUpdateForm
    second_form_class = ProfileUpdateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(instance=self.object)
        if 'form2' not in context:
            context['form2'] = self.second_form_class(instance=self.object.habrprofile)
        context['avatar'] = self.object.avatar
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form2 = self.second_form_class(request.POST, instance=self.object.habrprofile)
        form = self.form_class(request.POST, instance=self.object)
        if form.is_valid() and form2.is_valid():
            form2.save()
            return super().post(request, *args, **kwargs)
        else:
            return self.render_to_response(
                self.get_context_data(form=form, form2=form2))


class UserDeleteView(UserIsPersonalMixin, DeleteView):
    model = HabUser
    template_name = 'adminapp/users/user_delete.html'
    success_url = reverse_lazy('_admin:users')
    context_object_name = 'user_to_delete'


# контроллеры для категорий
class CategoryListView(UserIsPersonalMixin, ListView):
    model = Category
    template_name = 'adminapp/categories/categories.html'
    context_object_name = 'objects'
    paginate_by = 10


class CategoryCreateView(UserIsAdminMixin, CreateView):
    model = Category
    form_class = CategoryCreateForm
    template_name = 'adminapp/categories/category_create.html'
    success_url = reverse_lazy('_admin:categories')


class CategoryUpdateView(UserIsAdminMixin, UpdateView):
    model = Category
    form_class = CategoryCreateForm
    template_name = 'adminapp/categories/category_update.html'
    success_url = reverse_lazy('_admin:categories')


class CategoryDeleteView(UserIsAdminMixin, DeleteView):
    model = Category
    template_name = 'adminapp/categories/category_delete.html'
    success_url = reverse_lazy('_admin:categories')
    context_object_name = 'category_to_delete'


# контроллеры для статей
class HabsListView(UserIsPersonalMixin, ListView):
    model = Hab
    template_name = 'adminapp/habs/habs.html'
    context_object_name = 'objects'
    paginate_by = 10


class HabCreateView(UserIsPersonalMixin, CreateView):
    model = Hab
    form_class = HabCreateForm
    template_name = 'adminapp/habs/hab_create.html'
    success_url = reverse_lazy('_admin:habs')


class HabUpdateView(UserIsAdminMixin, UpdateView):
    model = Hab
    form_class = HabUpdateForm
    template_name = 'adminapp/habs/hab_update.html'
    success_url = reverse_lazy('_admin:habs')


class HabDeleteView(UserIsPersonalMixin, DeleteView):
    model = Hab
    template_name = 'adminapp/habs/hab_delete.html'
    context_object_name = 'hab_to_delete'
    success_url = reverse_lazy('_admin:habs')


# контроллеры для комментов
class CommnetsListView(UserIsPersonalMixin, ListView):
    model = Comments
    template_name = 'adminapp/comments/comments.html'
    context_object_name = 'objects'
    paginate_by = 10


class CommentCreateView(UserIsPersonalMixin, CreateView):
    model = Comments
    form_class = CommentCreateForm
    template_name = 'adminapp/comments/comment_create.html'
    success_url = reverse_lazy('_admin:comments')


class CommentUpdateView(UserIsAdminMixin, UpdateView):
    model = Comments
    form_class = CommentUpdateForm
    template_name = 'adminapp/comments/comment_update.html'
    success_url = reverse_lazy('_admin:comments')


class CommentDeleteView(UserIsPersonalMixin, DeleteView):
    model = Comments
    template_name = 'adminapp/comment/comment_delete.html'
    context_object_name = 'comment_to_delete'
    # success_url = reverse_lazy('_admin:comments')

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')

# # контроллеры для новостей
# class NewsListView(UserIsPersonalMixin, ListView):
#     model = News
#     template_name = 'adminapp/news/news.html'
#     context_object_name = 'objects'
#     paginate_by = 10
#
#
# class NewsCreateView(UserIsPersonalMixin, CreateView):
#     model = News
#     form_class = NewsCreateForm
#     template_name = 'adminapp/news/news_create.html'
#     success_url = reverse_lazy('_admin:news')
#
#     def post(self, request, *args, **kwargs):
#         form = self.get_form()
#         if form.is_valid():
#             news = form.save(commit=False)
#             news.author = request.user
#             self.object = form.save()
#             return super().form_valid(form)
#
#
# class NewsUpdateView(UserIsPersonalMixin, UpdateView):
#     model = News
#     form_class = NewsUpdateForm
#     template_name = 'adminapp/news/news_update.html'
#     success_url = reverse_lazy('_admin:news')
#
#
# class NewsDeleteView(UserIsPersonalMixin, DeleteView):
#     model = News
#     template_name = 'adminapp/news/news_delete.html'
#     context_object_name = 'news_to_delete'
#     success_url = reverse_lazy('_admin:news')


# контролеры для модерации
class ModerListView(UserIsPersonalMixin, TemplateView):
    template_name = 'adminapp/moder/moder.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['habs'] = Hab.objects.all().filter(approve=False, status='PB')
        context['notifications'] = NotifyComment.objects.all().filter(is_read=False)
        # context['news'] = News.objects.all().filter(status='DF')
        return context


class ApproveHab(UserIsPersonalMixin, UpdateView):
    model = Hab
    template_name = 'adminapp/moder/hab_approve.html'
    success_url = reverse_lazy('_admin:moder')
    form_class = ApproveHabForm

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.approve = True
        self.object.publication_date = timezone.now()
        self.object.save(update_fields=['approve', 'publication_date'])
        # self.object.save()
        return super().post(request, *args, **kwargs)


# class ApproveNews(UserIsPersonalMixin, UpdateView):
#     model = News
#     template_name = 'adminapp/moder/news_approve.html'
#     success_url = reverse_lazy('_admin:moder')
#     form_class = ApproveNewsForm
#
#     def post(self, request, *args, **kwargs):
#         self.object = self.get_object()
#         self.object.status = 'PB'
#         self.object.date = timezone.now()
#         self.object.save()
#         return super().post(request, *args, **kwargs)


class NotifyDeleteView(UserIsPersonalMixin, DeleteView):
    model = NotifyComment
    success_url = reverse_lazy('_admin:moder')


class UserBlock(UserIsPersonalMixin, DeleteView):
    model = HabUser

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')

    def delete(self, request, *args, **kwargs):
        """  """
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.user_block()
        return HttpResponseRedirect(success_url)

adminapp/templates/adminapp/categories/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block css %}
<link href="{% static 'adminapp/css/admin_style.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
<section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <ol>
          <li><a href="/">Главная</a></li>
          <li><a href="{% url '_admin:main_admin' %}">Админка</a></li>
          <li>Категории</li>
        </ol>
        <h2>Категории</h2>

      </div>
</section>

<div class="container items-wrapper overflow-auto h-auto">
    {% if request.user.role == "A" %}
    <div class="row">
        <div class="col-sm-12 d-flex justify-content-end ">
            <a href="{% url '_admin:category_create' %}" class="btn btn-outline-secondary m-b20-r10">
                Создать категорию
            </a>
        </div>
    </div>
    {% endif %}
    {% for category in objects %}
        <div class="item-block shadow row {% if not category.is_active %} is-deleted {% endif %}">
            <div class="col-sm-1">{{ forloop.counter }}</div>
            <div class="col-sm-9 row">
                <div class="col-sm-4"><span>{{ category.name }}</span></div>
                <div class="w-100 d-none d-md-block"></div>
                <div class="col-sm-4"></div>
                <div class="col-sm-6"></div>
                <div class="col-sm-2"></div>
            </div>
            <div class="col-sm-2 row-cols-2">
                {% if request.user.role == 'A' or request.user.is_superuser %}
                    <div class="col-sm-12 mar-b-5">
                        <a href="{% url '_admin:category_update' category.pk %}"
                            class="btn btn-outline-secondary btn-block align-items-start d-b">Редактировать</a>
                    </div>

                <div class="col-sm-12">
<!--                    <a href="{% url '_admin:category_delete' category.pk %}"-->
<!--                       class="btn btn-outline-secondary btn-block align-items-end d-b">-->
<!--                        {% if category.is_active %} del {% else %} restore {% endif %}</a>-->
                    <form method="POST" action="{% url '_admin:category_delete' category.pk %}">
                        {% csrf_token %}
                        <input class="btn btn-outline-secondary btn-block align-items-end d-b w-100"
                               type="submit" value="{% if category.is_active %} del {% else %} restore {% endif %}">
                    </form>
                </div>
                {% endif %}
            </div>
        </div>
    {% endfor %}
    {% include 'adminapp/includes/pagination.html' %}
</div>
{% endblock content %}

adminapp/templates/adminapp/categories/category_create.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block css %}
<link href="{% static 'adminapp/css/admin_style.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
<section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <ol>
          <li><a href="/">Главная</a></li>
          <li><a href="{% url '_admin:main_admin' %}">Админка</a></li>
          <li><a href="{% url '_admin:categories' %}">Категории</a></li>
            <li>Создание</li>
        </ol>
        <h2>Создание</h2>

      </div>
</section>
<div class="container items-wrapper overflow-auto h-auto">
    <div class="row">
        <div class="col-sm-12 d-flex justify-content-end ">
            <a href="{% url '_admin:categories' %}" class="btn btn-outline-secondary m-b20-r10">
                К списку категорий
            </a>
        </div>
    </div>
    <div class="item-block shadow row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <form class="form-horizontal" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Создать" class="btn btn-outline-secondary">
            </form>
        </div>
        <div class="col-sm-3"></div>
    </div>
</div>
{% endblock content %}

adminapp/templates/adminapp/categories/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block css %}
<link href="{% static 'adminapp/css/admin_style.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
<section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <ol>
          <li><a href="/">Главная</a></li>
          <li><a href="{% url '_admin:main_admin' %}">Админка</a></li>
          <li><a href="{% url '_admin:categories' %}">Категории</a></li>
            <li>Удаление</li>
        </ol>
        <h2>Удаление</h2>

      </div>
</section>

<div class="container items-wrapper overflow-auto h-auto">
    <div class="item-block shadow row justify-content-center">
        <div class="col-sm-4 align-self-center">
            Вы точно хотите
            {% if category_to_delete.is_active %} удалить {% else %} восстановить {% endif %}
            категорию "{{ category_to_delete.name }}" ?
        </div>
        <div class="col-sm-1 align-self-center">
            <form class="form-horizontal" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="submit" class="btn btn-outline-secondary"
                       value="{% if category_to_delete.is_active %} Удалить {% else %} Восстановить {% endif %}">
            </form>
        </div>
        <div class="col-sm-3 align-self-center">
            <a href="{% url '_admin:categories' %}" class="btn btn-outline-secondary">
                К списку категорий
            </a>
        </div>
    </div>
</div>
{% endblock content %}

adminapp/templates/adminapp/categories/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block css %}
<link href="{% static 'adminapp/css/admin_style.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
<section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <ol>
          <li><a href="/">Главная</a></li>
          <li><a href="{% url '_admin:main_admin' %}">Админка</a></li>
          <li><a href="{% url '_admin:categories' %}">Категории</a></li>
            <li>Редактирование</li>
        </ol>
        <h2>Редактирование</h2>

      </div>
</section>
<div class="container items-wrapper overflow-auto h-auto">
    <div class="row">
        <div class="col-sm-12 d-flex justify-content-end ">
            <a href="{% url '_admin:categories' %}" class="btn btn-outline-secondary m-b20-r10">
                К списку категорий
            </a>
            <a href="{% url '_admin:category_create' %}" class="btn btn-outline-secondary m-b20-r10">
                Создать категорию
            </a>
        </div>
    </div>
    <div class="item-block shadow row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <form class="form-horizontal" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Сохранить" class="btn btn-outline-secondary">
            </form>
        </div>
        <div class="col-sm-3"></div>
    </div>
</div>
{% endblock content %}